questions = [
    {"prompt": "What is the capital of France?",
     "options": ["A) Paris", "B) Dubai", "C) Berlin", "D) Madrid"],
     "answer": "A"},
    {"prompt": "What is the capital of Spain?",
     "options": ["A) Paris", "B) London", "C) New York", "D) Madrid"],
     "answer": "D"},
    {"prompt": "What is the capital of Germany?",
     "options": ["A) Hamburg", "B) London", "C) Berlin", "D) Madrid"],
     "answer": "C"},
    {"prompt": "What is the capital of England?",
     "options": ["A) Paris", "B) London", "C) Berlin", "D) Madrid"],
     "answer": "B"},
    {"prompt": "What is the capital of Italy?",
     "options": ["A) Rome", "B) Milan", "C) Naples", "D) Florence"],
     "answer": "A"},
    {"prompt": "What is the capital of China?",
     "options": ["A) Beijing", "B) Shanghai", "C) Guangzhou", "D) Hong Kong"],
     "answer": "A"},
    {"prompt": "What is the capital of Japan?",
     "options": ["A) Tokyo", "B) Osaka", "C) Nagoya", "D) Sapporo"],
     "answer": "A"},
    {"prompt": "What is the capital of Brazil?",
     "options": ["A) Rio de Janeiro", "B) São Paulo", "C) Brasilia", "D) Lima"],
     "answer": "C"},
    {"prompt": "What is the capital of Mexico?",
     "options": ["A) Mexico City", "B) Guadalajara", "C) Monterrey", "D) Puebla"],
     "answer": "A"},
    {"prompt": "What is the capital of Russia?",
     "options": ["A) Moscow", "B) St. Petersburg", "C) Ekaterinburg", "D) Novosibirsk"],
     "answer": "A"},
    {"prompt": "What is the capital of India?",
     "options": ["A) New Delhi", "B) Mumbai", "C) Bangalore", "D) Chennai"],
     "answer": "A"},
    {"prompt": "What is the capital of Australia?",
     "options": ["A) Sydney", "B) Melbourne", "C) Brisbane", "D) Canberra"],
     "answer": "D"},
    {"prompt": "What is the capital of Canada?",
     "options": ["A) Toronto", "B) Montreal", "C) Vancouver", "D) Ottawa"],
     "answer": "D"}
]